export const API_LINK = {
  Login: "auth/login",
  Me: "auth/me",
  Refresh: "auth/refresh",
  Logout: "auth/logout",
  Account: "account",
  AccountPassword: "account/password",
  AccountSessions: "account/sessions",
  AccountSession: (id) => `account/sessions/${id}`,
  Role: "role",
  RoleOptions: "role/options",
  RoleDetails: (id) => `role/${id}`,
  Company: "company",
  CompanyDetails: (id) => `company/${id}`,
  CompanyStatus: (id) => `company/${id}/status`,
  Outlet: "outlet",
  OutletDetails: (id) => `outlet/${id}`,
  OutletStatus: (id) => `outlet/${id}/status`,
  OutletItems: (id) => `outlet/${id}/items`,
  Staff: "staff",
  StaffDetails: (id) => `staff/${id}`,
  StaffStatus: (id) => `staff/${id}/status`,
  StaffTransfer: (id) => `staff/${id}/transfer`,
  StaffAssignments: (id) => `staff/${id}/assignments`,
  Menu: "menu",
  MenuDetails: (id) => `menu/${id}`,
  MenuStatus: (id) => `menu/${id}/status`,
  MenuItem: "menu-item",
  MenuItemDetails: (id) => `menu-item/${id}`,
  MenuItemOutlets: (id) => `menu-item/${id}/outlets`,
  MenuItemOutlet: (id, outletId) => `menu-item/${id}/outlets/${outletId}`,
  SalesOrder: "sales-order",
  SalesOrderItems: "sales-order/items",
  SalesOrderDetails: (id) => `sales-order/${id}`,
  SalesOrderComplete: (id) => `sales-order/${id}/complete`,
  SalesOrderCancel: (id) => `sales-order/${id}/cancel`,
  SalesOrderSlip: (id) => `sales-order/${id}/slip`,
  CompanyDashboard: "dashboard/company",
  CompanyOutletSales: "dashboard/company/outlets",
  CompanyActivity: "dashboard/company/activity",
  CompanyTrend: "dashboard/company/trend",
  CompanyAlerts: "dashboard/company/alerts",
  CompanyAlertDetail: (type) => `dashboard/company/alerts/${type}`,
  OutletDashboard: "dashboard/outlet",
  OutletLowStock: "dashboard/outlet/low-stock",
  OutletNotices: "dashboard/outlet/notices",
  OutletPopularItems: "dashboard/outlet/popular-items",
  OutletStaffSchedule: "dashboard/outlet/staff-schedule",
  Shift: "shift",
  ShiftDetails: (id) => `shift/${id}`,
  ShiftMe: "shift/me",
  ShiftStart: "shift/start",
  ShiftEnd: "shift/end",
  ShiftBreakStart: "shift/break/start",
  ShiftBreakEnd: "shift/break/end",
  Report: (type) => `report/${type}`,
  Reminder: "reminder",
  ReminderDetails: (id) => `reminder/${id}`,
  ReminderDone: (id) => `reminder/${id}/done`,
  ReminderReplies: (id) => `reminder/${id}/replies`,
  UploadImage: (folder) => `upload/image?folder=${folder}`,
};
