export const API_LINK = {
  Login: "auth/login",
  Company: "company",
  CompanyDetails: (id) => `company/${id}`,
  CompanyStatus: (id) => `company/${id}/status`,
  Outlet: "outlet",
  OutletDetails: (id) => `outlet/${id}`,
  OutletStatus: (id) => `outlet/${id}/status`,
  OutletItems: (id) => `outlet/${id}/items`,
  Staff: "staff",
  StaffDetails: (id) => `staff/${id}`,
  StaffStatus: (id) => `staff/${id}/status`,
  StaffTransfer: (id) => `staff/${id}/transfer`,
  StaffAssignments: (id) => `staff/${id}/assignments`,
  Menu: "menu",
  MenuDetails: (id) => `menu/${id}`,
  MenuStatus: (id) => `menu/${id}/status`,
  MenuItem: "menu-item",
  MenuItemDetails: (id) => `menu-item/${id}`,
  MenuItemOutlets: (id) => `menu-item/${id}/outlets`,
  MenuItemOutlet: (id, outletId) => `menu-item/${id}/outlets/${outletId}`,
  UploadImage: (folder) => `upload/image?folder=${folder}`,
};
